/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/documents': RouteRecordInfo<
      '/documents',
      '/documents',
      Record<never, never>,
      Record<never, never>,
      | '/documents/'
    >,
    '/documents/': RouteRecordInfo<
      '/documents/',
      '/documents',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs': RouteRecordInfo<
      '/jobs',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | '/jobs/'
      | '/jobs/[jobId]'
      | '/jobs/new'
    >,
    '/jobs/': RouteRecordInfo<
      '/jobs/',
      '/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/jobs/[jobId]': RouteRecordInfo<
      '/jobs/[jobId]',
      '/jobs/:jobId',
      { jobId: ParamValue<true> },
      { jobId: ParamValue<false> },
      | never
    >,
    '/jobs/new': RouteRecordInfo<
      '/jobs/new',
      '/jobs/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/appearance'
      | '/settings/email'
      | '/settings/import-export'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/email': RouteRecordInfo<
      '/settings/email',
      '/settings/email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/import-export': RouteRecordInfo<
      '/settings/import-export',
      '/settings/import-export',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/pages/documents.vue': {
      routes:
        | '/documents'
        | '/documents/'
      views:
        | 'default'
    }
    'src/pages/documents/index.vue': {
      routes:
        | '/documents/'
      views:
        | never
    }
    'src/pages/jobs.vue': {
      routes:
        | '/jobs'
        | '/jobs/'
        | '/jobs/[jobId]'
        | '/jobs/new'
      views:
        | 'default'
    }
    'src/pages/jobs/index.vue': {
      routes:
        | '/jobs/'
      views:
        | never
    }
    'src/pages/jobs/[jobId].vue': {
      routes:
        | '/jobs/[jobId]'
      views:
        | never
    }
    'src/pages/jobs/new.vue': {
      routes:
        | '/jobs/new'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/appearance'
        | '/settings/email'
        | '/settings/import-export'
      views:
        | 'default'
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/settings/email.vue': {
      routes:
        | '/settings/email'
      views:
        | never
    }
    'src/pages/settings/import-export.vue': {
      routes:
        | '/settings/import-export'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
